#!/bin/bash
# Langflow — deploy/manage. Run with: bash deploy.sh
#
# See docker-compose.yml in this folder for every way this deployment differs
# from upstream's own, and why.

set -euo pipefail

SERVICE_NAME="langflow"
# Pinned, and here `latest` would have been fine — checked, not assumed:
# `latest` and `1.11.4` carry the SAME registry digest, and the newer
# `1.12.0.devNN` tags are excluded from it. Pinned anyway so a redeploy in six
# months lands on the image this was tested against, not on whatever `latest`
# has become by then.
LANGFLOW_VERSION_PIN="1.11.4"
SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNTIME_DIR="$HOME/docker/$SERVICE_NAME"
LOGFILE="$RUNTIME_DIR/deploy.log"
CONTAINER_PORT=7860

LIB_COMMON="$SOURCE_DIR/../../../lib/common.sh"
if [[ ! -f "$LIB_COMMON" ]]; then
    LIB_COMMON="$(mktemp -d)/common.sh"
    curl -fsSL -o "$LIB_COMMON" "https://raw.githubusercontent.com/IbrahimAljuhani/dockhub/main/lib/common.sh"
fi
# shellcheck source=/dev/null
source "$LIB_COMMON"

if [[ $EUID -eq 0 ]]; then
    print_error "This script must NOT be run as root. Please run as a regular user in the docker group."
fi

check_prerequisites
ensure_main_net
# The network is joined unconditionally now, so it must exist even on a host
# that has never deployed anything from the AI category.
ensure_models_net

[[ -f "$SOURCE_DIR/docker-compose.yml" ]] || print_error "docker-compose.yml not found in $SOURCE_DIR."

mkdir -p "$RUNTIME_DIR"

if [[ -f "$RUNTIME_DIR/docker-compose.yml" ]]; then
    print_info "Existing deployment found at $RUNTIME_DIR — its secrets and data are kept."

    # ── Changes a kept compose cannot pick up, and MUST ──────────────────
    # 1. 'models-net'. The override written below joins it unconditionally and
    #    the base compose DECLARES it. A kept file from before declares no such
    #    network, so the merged project references an undefined one:
    #    `compose config -q` rejects it and this script stops. Failing safely
    #    is still failing, so the file is replaced rather than warned about.
    # 2. LANGFLOW_ENABLE_SIGNUP=False. Upstream's default is True, which
    #    leaves POST /api/v1/users/ open — an unauthenticated endpoint that
    #    creates accounts. A deployment left on the old file keeps it open.
    #
    # NOTE THE KEY THIS TESTS. It was 'ai-net' for one day (2026-08-19), then
    # became 'models-net' when that turned out to connect code-running builders
    # to OpenHands — which has no authentication and holds the Docker socket.
    # A guard left pointing at the OLD name would find ai-net in an old file,
    # decide there was nothing to do, and leave the deployment referencing a
    # network nobody declared. The guard must always name what the CURRENT
    # source file declares.
    #
    # Replacing is safe here in a way it would not be for a hand-tuned file:
    # this compose is generated by DockHub, and the deployment's data lives in
    # ./data and a named volume, neither of which is touched. The previous
    # file is kept beside the new one all the same.
    if ! grep -qE '^[[:space:]]+models-net:' "$RUNTIME_DIR/docker-compose.yml"; then
        cp "$RUNTIME_DIR/docker-compose.yml" "$RUNTIME_DIR/docker-compose.yml.pre-modelsnet"
        cp "$SOURCE_DIR/docker-compose.yml" "$RUNTIME_DIR/docker-compose.yml"
        print_info "Updated this deployment's compose file. Two changes:"
        print_info "  · moved to 'models-net' — it still reaches an Ollama / llama.cpp /"
        print_info "    LocalAI by container name (http://ollama:11434), but is no longer"
        print_info "    on the same network as OpenHands, which has no authentication"
        print_info "    and holds the Docker socket."
        print_info "  · closes public signup (LANGFLOW_ENABLE_SIGNUP=False). Upstream"
        print_info "    defaults it to True, leaving an unauthenticated endpoint that"
        print_info "    creates accounts. Add users as the superuser instead."
        print_info "Previous compose kept as docker-compose.yml.pre-modelsnet"
    fi
else
    cp "$SOURCE_DIR/docker-compose.yml" "$RUNTIME_DIR/"

    # ── Secrets ──────────────────────────────────────────────────────────
    # Upstream's .env.example is unusually clean: unlike Dify and Flowise it
    # ships NO credential defaults at all, only empty keys. The published
    # credentials are in their COMPOSE file instead —
    #   LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
    #   POSTGRES_PASSWORD: langflow
    # — which is why reading only the example file would have missed them.
    umask 077
    {
        echo "# Generated by deploy.sh — do not commit. Secrets live here only."
        echo "LANGFLOW_VERSION=$LANGFLOW_VERSION_PIN"
        echo "POSTGRES_USER=langflow"
        echo "POSTGRES_PASSWORD=$(generate_secret 32)"
        echo "POSTGRES_DB=langflow"
        echo "LANGFLOW_SUPERUSER=admin"
        echo "LANGFLOW_SUPERUSER_PASSWORD=$(generate_secret 24)"
        # ── This one is NOT generate_secret_hex, and the difference matters ─
        # LANGFLOW_SECRET_KEY encrypts every stored credential (Langflow's
        # "global variables" of type Secret — your model-provider API keys)
        # using Fernet, which requires a key that decodes to EXACTLY 32 bytes.
        # Measured, not assumed:
        #   generate_secret_hex 32 → 64 chars → 48 bytes → REJECTED
        #   generate_secret 32     → 32 chars → 24 bytes → REJECTED
        #   generate_secret_urlsafe 32 → 43 chars → 32 bytes → valid
        # This is the same value Langflow's own docs tell you to produce with
        # python -c "from secrets import token_urlsafe; print(token_urlsafe(32))".
        echo "LANGFLOW_SECRET_KEY=$(generate_secret_urlsafe 32)"
    } > "$RUNTIME_DIR/.env"
    chmod 600 "$RUNTIME_DIR/.env"
    umask 022

    # Assert rather than announce. `langflow` as a USERNAME is upstream's and
    # is fine — it is the password of the same name that must not survive, so
    # the check is anchored to the places a password appears.
    if grep -qE '^POSTGRES_PASSWORD=langflow$|:langflow@' "$RUNTIME_DIR/.env"; then
        print_error "Upstream's published database password survived generation — bug in deploy.sh."
    fi

    # The key is worthless if it is the wrong shape, and the failure appears
    # later as an unreadable credential rather than as a startup error. So it
    # is checked here, where it was just written.
    _sk="$(read_env_value LANGFLOW_SECRET_KEY "$RUNTIME_DIR/.env")"
    if [[ ! "$_sk" =~ ^[A-Za-z0-9_-]{43}$ ]]; then
        print_error "Generated LANGFLOW_SECRET_KEY is not a valid Fernet key — bug in generate_secret_urlsafe."
    fi
    unset _sk

    print_info "Generated the database password, the admin password and the Fernet secret key."
fi

# ── The config directory, created before Docker can ──────────────────────
# The image runs as uid 1000 (`useradd user -u 1000 -g 0`). A bind-mount
# target that does not exist is created by the daemon as ROOT, and Langflow
# then cannot write its flows — it fails with a permission error naming a
# path inside the container, which is a poor clue to a problem out here.
#
# Outside the first-install branch on purpose, so a deployment made before
# this existed gets corrected on its next run rather than staying broken.
mkdir -p "$RUNTIME_DIR/data"
chmod 700 "$RUNTIME_DIR/data"
if [[ "$(id -u)" != "1000" ]]; then
    print_warn "This image runs as uid 1000 and you are uid $(id -u), so it cannot"
    print_warn "write to $RUNTIME_DIR/data. Fix it once with:"
    print_warn "    sudo chown -R 1000:0 $RUNTIME_DIR/data"
fi

# ── How it is reached ────────────────────────────────────────────────────
# Langflow's Custom Component nodes execute Python inside this container, so
# it belongs to the Multi-Agent threat model and gets that category's
# question — asked, not assumed.
ENV_HOST_PORT="$(read_env_value DOCKHUB_HOST_PORT "$RUNTIME_DIR/.env" || true)"
ENV_ON_MAIN_NET="$(read_env_value DOCKHUB_ON_MAIN_NET "$RUNTIME_DIR/.env" || true)"

if [[ ! -f "$RUNTIME_DIR/.dockhub-asked" ]]; then
    prompt_agent_network "Langflow" "models-net"
    ENV_ON_MAIN_NET="$AGENT_ON_MAIN_NET"
    if (( ENV_ON_MAIN_NET )); then
        prompt_host_port "$CONTAINER_PORT"
    else
        print_info "Not on 'main-net', so a host port is the only way to reach it."
        prompt_host_port "$CONTAINER_PORT" required
    fi
    ENV_HOST_PORT="${HOST_PORT:-}"
    set_env_value DOCKHUB_HOST_PORT   "$ENV_HOST_PORT"   "$RUNTIME_DIR/.env"
    set_env_value DOCKHUB_ON_MAIN_NET "$ENV_ON_MAIN_NET" "$RUNTIME_DIR/.env"
    prompt_mem_limit "langflow" "2g"
    [[ -n "$MEM_LIMIT" ]] && set_env_value DOCKHUB_MEM_LIMIT "$MEM_LIMIT" "$RUNTIME_DIR/.env"
    touch "$RUNTIME_DIR/.dockhub-asked"
fi
[[ -z "$ENV_ON_MAIN_NET" ]] && ENV_ON_MAIN_NET=1
ENV_MEM_LIMIT="$(read_env_value DOCKHUB_MEM_LIMIT "$RUNTIME_DIR/.env" || true)"
# The database's limit is settable but NOT prompted — add DOCKHUB_DB_MEM_LIMIT
# to .env by hand and rerun. Deliberately not a question: the deploy interview
# is already long, and a wrong answer here is worse than no answer. Postgres
# that hits a hard memory ceiling does not slow down, it gets OOM-killed
# mid-write, and the size it actually needs depends on the largest restore you
# will ever run, which nobody knows at deploy time. Documented in the README.
ENV_DB_MEM_LIMIT="$(read_env_value DOCKHUB_DB_MEM_LIMIT "$RUNTIME_DIR/.env" || true)"

# ── Regenerated every run, never hand-edited ─────────────────────────────
# Written whole rather than appended to, and its shape is checked below: the
# equivalent file for Dify was once built by appending a second `services:`
# block, which is a duplicate top-level key that Compose cannot read.
{
    echo "# Generated by deploy.sh on every run — never hand-edit."
    echo "services:"
    echo "  langflow:"
    [[ -n "$ENV_MEM_LIMIT" ]] && echo "    mem_limit: $ENV_MEM_LIMIT"
    if [[ -n "$ENV_HOST_PORT" ]]; then
        echo "    ports:"
        echo "      - \"$ENV_HOST_PORT:$CONTAINER_PORT\""
    fi
    # This file owns the APP's network membership outright — the base compose
    # gives the langflow service no `networks:` key at all, precisely so that
    # these lines REPLACE rather than merge with it.
    echo "    networks:"
    # Both of these are unconditional, and neither is a reachability choice:
    # one is the link to its own database, the other the link to a local
    # model provider. The base file declares them; only membership is written
    # here, because membership is what merges.
    echo "      - langflow-db-net"
    echo "      - models-net"
    if (( ENV_ON_MAIN_NET )); then
        echo "      - main-net"
    else
        # Its own private network, so the container still has one. A service
        # with no network at all lands on the default bridge, back among
        # every other unattached container on the host.
        echo "      - langflow-net"
    fi
    # Second service block, and only when asked for — an empty `langflow-db:`
    # key with nothing under it is a null value, not an empty map, and
    # Compose rejects the file.
    if [[ -n "$ENV_DB_MEM_LIMIT" ]]; then
        echo "  langflow-db:"
        echo "    mem_limit: $ENV_DB_MEM_LIMIT"
    fi
    echo "networks:"
    if (( ENV_ON_MAIN_NET )); then
        echo "  main-net:"
        echo "    external: true"
    else
        echo "  langflow-net:"
    fi
} > "$RUNTIME_DIR/docker-compose.override.yml"

_dupes="$(grep -oE '^[a-z_]+:' "$RUNTIME_DIR/docker-compose.override.yml" | sort | uniq -d)"
[[ -z "$_dupes" ]] || print_error "Generated an invalid override (duplicate top-level key: $_dupes). Bug in deploy.sh."
if ! (cd "$RUNTIME_DIR" && $COMPOSE_CMD config -q 2>/tmp/langflow-cfg.err); then
    print_warn "Compose rejected the merged configuration:"
    sed 's/^/    /' /tmp/langflow-cfg.err >&2
    rm -f /tmp/langflow-cfg.err
    print_error "Refusing to continue with a configuration Compose cannot read."
fi
rm -f /tmp/langflow-cfg.err

# Before anything is pulled or started: is this rerun quietly an upgrade?
confirm_version_change "langflow" \
    "langflowai/langflow:$(read_env_value LANGFLOW_VERSION "$RUNTIME_DIR/.env")" \
    "Langflow"

# And is the kept compose file behind the one in this repo? Only informs.
offer_compose_update "$RUNTIME_DIR/docker-compose.yml" "$SOURCE_DIR/docker-compose.yml" \
    "rm $RUNTIME_DIR/docker-compose.yml && bash $0"

pull_with_progress "$RUNTIME_DIR"

print_info "Starting $SERVICE_NAME..."
(cd "$RUNTIME_DIR" && $COMPOSE_CMD up -d 2>&1 | tee -a "$LOGFILE") \
    || print_error "Failed to start $SERVICE_NAME. Check log: $LOGFILE"

# /health_check, NOT /health. Upstream documents the difference: /health is
# answered by uvicorn BEFORE Langflow finishes initialising, so probing it
# would turn this wait into a false pass. curl is present in this RHEL-based
# image; wget is not.
#
# The wait is generous because Langflow imports its whole component library
# at startup — first boot is minutes, not seconds, on a small server.
print_info "Waiting for Langflow to finish initialising (first start is slow)..."
if wait_for_container_ready "langflow" \
     "curl -fsS -o /dev/null http://localhost:$CONTAINER_PORT/health_check" 40 6; then
    print_info "Langflow is answering."
else
    print_warn "Langflow did not answer within 240s. Check:  docker logs -f langflow"
fi

echo
echo "──────────────────────────────────────────────"
if [[ -n "$ENV_HOST_PORT" ]]; then
    echo "🌐 URL:        http://$(host_lan_ip):$ENV_HOST_PORT"
fi
if (( ENV_ON_MAIN_NET )); then
    echo "🔗 Proxy:      langflow:$CONTAINER_PORT on 'main-net'"
else
    echo "🔒 Networks:   langflow-net only — deliberately NOT on 'main-net'"
fi
# Printed in full because it is generated, not chosen — there is no other
# way to learn it. Qualified with "at first start" because Langflow creates
# the superuser once: change the password in the UI and this .env value goes
# stale, so an unqualified "Login:" line would become a lie on every rerun.
echo "👤 Login:      $(read_env_value LANGFLOW_SUPERUSER "$RUNTIME_DIR/.env")  /  $(read_env_value LANGFLOW_SUPERUSER_PASSWORD "$RUNTIME_DIR/.env")   (as set at first start)"
echo "🗄️  Database:   postgres in 'langflow-db' — no host port, not on main-net"
echo "📁 Flows:      $RUNTIME_DIR/data"
echo "🔑 Secrets:    $RUNTIME_DIR/.env   (chmod 600)"
echo "📜 Log:        $LOGFILE"
echo "──────────────────────────────────────────────"
echo
print_warn "Custom Component nodes run PYTHON inside this container. Treat a flow"
print_warn "you did not write like a script you did not write."
print_warn "See services/Multi-Agent/README.md."
echo
echo "To manage: cd $RUNTIME_DIR && $COMPOSE_CMD [ps|logs -f|stop|restart]"
print_tunnel_reminder_if_relevant
