#!/bin/bash
# Paperclip — deploy/manage. Run with: bash deploy.sh
#
# See docker-compose.yml in this folder for why this service exists now (a
# condition written into services/Multi-Agent/README.md was met on
# 2026-08-18) and why it pulls rather than builds.

set -euo pipefail

SERVICE_NAME="paperclip"
SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNTIME_DIR="$HOME/docker/$SERVICE_NAME"
LOGFILE="$RUNTIME_DIR/deploy.log"
CONTAINER_PORT=3100

LIB_COMMON="$SOURCE_DIR/../../../lib/common.sh"
if [[ ! -f "$LIB_COMMON" ]]; then
    LIB_COMMON="$(mktemp -d)/common.sh"
    curl -fsSL -o "$LIB_COMMON" "https://raw.githubusercontent.com/IbrahimAljuhani/dockhub/main/lib/common.sh"
fi
# shellcheck source=/dev/null
source "$LIB_COMMON"

if [[ $EUID -eq 0 ]]; then
    print_error "This script must NOT be run as root. Please run as a regular user in the docker group."
fi

check_prerequisites
ensure_main_net

[[ -f "$SOURCE_DIR/docker-compose.yml" ]] || print_error "docker-compose.yml not found in $SOURCE_DIR."

mkdir -p "$RUNTIME_DIR"

if [[ -f "$RUNTIME_DIR/docker-compose.yml" ]]; then
    print_info "Existing deployment found at $RUNTIME_DIR — reusing its .env (source files not re-copied)."
else
    cp "$SOURCE_DIR/docker-compose.yml" "$RUNTIME_DIR/"

    # ── The reachable address, decided before anything is written ────────
    # PAPERCLIP_PUBLIC_URL is not cosmetic. Paperclip builds its login and
    # session-cookie redirects from it, so a value that does not match the
    # address you actually type produces a login page that bounces you back
    # to itself — the failure this repo already hit on OpenProject,
    # Nextcloud and n8n independently before it became a fixed convention.
    prompt_host_port "$CONTAINER_PORT"

    if [[ -n "$HOST_PORT" ]]; then
        # Direct access: the URL must be the IP and port a browser will use,
        # not a domain that does not resolve yet.
        SERVER_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
        [[ -n "$SERVER_IP" ]] || SERVER_IP="localhost"
        PUBLIC_URL="http://${SERVER_IP}:${HOST_PORT}"
        print_info "Public URL set to $PUBLIC_URL (direct host port)."
    else
        prompt_domain "Public domain for Paperclip (e.g. agents.example.com): " "domain"
        PUBLIC_URL="https://$PROMPTED_DOMAIN"
        print_info "Public URL set to $PUBLIC_URL — point NGINX Proxy Manager at paperclip-app:$CONTAINER_PORT."
    fi

    prompt_mem_limit "paperclip" "2g"

    # ── Secrets ──────────────────────────────────────────────────────────
    # BETTER_AUTH_SECRET is marked required upstream with `:?`, i.e. their own
    # compose refuses to start without it. Generated here so it is never a
    # weak default and never the same on two hosts.
    umask 077
    {
        echo "# Generated by deploy.sh — do not commit. Secrets live here only."
        echo "PAPERCLIP_VERSION=latest"
        echo "POSTGRES_USER=paperclip"
        echo "POSTGRES_PASSWORD=$(generate_secret)"
        echo "POSTGRES_DB=paperclip"
        echo "BETTER_AUTH_SECRET=$(generate_secret_hex 32)"
        echo "PUBLIC_URL=$PUBLIC_URL"
        [[ -n "$MEM_LIMIT" ]] && echo "MEM_LIMIT=$MEM_LIMIT"
        [[ -n "$HOST_PORT" ]] && echo "HOST_PORT=$HOST_PORT"
    } > "$RUNTIME_DIR/.env"
    chmod 600 "$RUNTIME_DIR/.env"
    umask 022

    # The bind mount's target, created before compose does. Left to Docker it
    # would be created root-owned, and a container running as uid 1000 then
    # cannot write its own instance config.
    mkdir -p "$RUNTIME_DIR/state"

    print_info "Copied service files to $RUNTIME_DIR."
fi

# ── Regenerated every run, never hand-edited ────────────────────────────
# To change these later: edit MEM_LIMIT=/HOST_PORT= in $RUNTIME_DIR/.env (or
# delete the line), then rerun this script.
ENV_MEM_LIMIT="$(read_env_value MEM_LIMIT "$RUNTIME_DIR/.env" || true)"
ENV_HOST_PORT="$(read_env_value HOST_PORT "$RUNTIME_DIR/.env" || true)"

if [[ -n "$ENV_MEM_LIMIT" || -n "$ENV_HOST_PORT" ]]; then
    {
        echo "services:"
        echo "  paperclip:"
        [[ -n "$ENV_MEM_LIMIT" ]] && echo "    mem_limit: $ENV_MEM_LIMIT"
        if [[ -n "$ENV_HOST_PORT" ]]; then
            echo "    ports:"
            echo "      - \"$ENV_HOST_PORT:$CONTAINER_PORT\""
        fi
    } > "$RUNTIME_DIR/docker-compose.override.yml"
    [[ -n "$ENV_MEM_LIMIT" ]] && print_info "Memory limit $ENV_MEM_LIMIT applied to paperclip-app (db stays unbounded)."
    [[ -n "$ENV_HOST_PORT" ]] && print_info "Host port $ENV_HOST_PORT published for direct access."
else
    rm -f "$RUNTIME_DIR/docker-compose.override.yml"
fi

pull_with_progress "$RUNTIME_DIR"

print_info "Starting $SERVICE_NAME..."
(cd "$RUNTIME_DIR" && $COMPOSE_CMD up -d 2>&1 | tee -a "$LOGFILE") \
    || print_error "Failed to start $SERVICE_NAME. Check log: $LOGFILE"

# ── Self-test ───────────────────────────────────────────────────────────
# Probes from INSIDE the container against its own port, so this tests the
# app rather than the host's networking. `wait_for_container_ready` reports a
# crash-loop as a death instead of waiting out the full timeout — the whole
# reason it exists.
#
# The probe is a TCP connect, deliberately not an HTTP path: this deployment
# runs in "authenticated" mode, so every route worth naming answers 401 or
# 302 until you have an account. Treating that as failure would report a
# healthy service as broken, which is the mistake already made once on
# Hermes. What is being asserted here is narrow and true — the server is
# listening. Whether you can log in is the next section's job, and yours.
print_info "Waiting for Paperclip to accept connections..."
if wait_for_container_ready "paperclip-app" \
     "node -e 'require(\"net\").connect($CONTAINER_PORT,\"127.0.0.1\").on(\"connect\",()=>process.exit(0)).on(\"error\",()=>process.exit(1))'" \
     30 5; then
    print_info "Paperclip is listening on $CONTAINER_PORT."
else
    rc=$?
    if (( rc == 1 )); then
        print_warn "paperclip-app stopped while starting up. Its last lines are above."
    else
        print_warn "Paperclip did not answer within 150s. It may still be migrating the database on first boot."
    fi
    print_warn "Check with:  docker logs -f paperclip-app"
fi

echo
print_info "$SERVICE_NAME is running."
echo "  Proxy target for NPM : paperclip-app:$CONTAINER_PORT  (on main-net)"
echo "  Public URL           : $(read_env_value PUBLIC_URL "$RUNTIME_DIR/.env" || echo '?')"
echo "  Data                 : $RUNTIME_DIR/state   (agent teams, goals, tickets)"
echo "  Credentials file     : $RUNTIME_DIR/.env    (chmod 600)"
echo
echo "  First run: open the URL above and create the first account. Paperclip"
echo "  runs in 'authenticated' mode — there is no anonymous access, and no"
echo "  default password for anyone to find."
echo
echo "  Paperclip manages agents; it does not include one. Give it a model"
echo "  provider by adding a key to $RUNTIME_DIR/.env and rerunning:"
echo "      OPENAI_API_KEY=sk-..."
echo "      ANTHROPIC_API_KEY=sk-ant-..."
echo "  Both are passed straight through by env_file and are optional."
print_tunnel_reminder_if_relevant
