#!/bin/bash
# Paperclip — deploy/manage. Run with: bash deploy.sh
#
# See docker-compose.yml in this folder for why this service exists now (a
# condition written into services/Multi-Agent/README.md was met on
# 2026-08-18) and why it pulls rather than builds.

set -euo pipefail

SERVICE_NAME="paperclip"
SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNTIME_DIR="$HOME/docker/$SERVICE_NAME"
LOGFILE="$RUNTIME_DIR/deploy.log"
CONTAINER_PORT=3100

LIB_COMMON="$SOURCE_DIR/../../../lib/common.sh"
if [[ ! -f "$LIB_COMMON" ]]; then
    LIB_COMMON="$(mktemp -d)/common.sh"
    curl -fsSL -o "$LIB_COMMON" "https://raw.githubusercontent.com/IbrahimAljuhani/dockhub/main/lib/common.sh"
fi
# shellcheck source=/dev/null
source "$LIB_COMMON"

if [[ $EUID -eq 0 ]]; then
    print_error "This script must NOT be run as root. Please run as a regular user in the docker group."
fi

check_prerequisites
# Both are created if missing. main-net is needed even in direct-port mode,
# because the compose file declares it as external — Compose resolves every
# declared network at `up`, whether or not a service attaches to it.
ensure_main_net
ensure_ai_net

[[ -f "$SOURCE_DIR/docker-compose.yml" ]] || print_error "docker-compose.yml not found in $SOURCE_DIR."

mkdir -p "$RUNTIME_DIR"

# ── How Paperclip is reached, asked in exactly one place ────────────────
# Defined as a function because it is needed on TWO paths — first install and
# reconfigure — and two copies of a question drift apart. Sets PUBLIC_URL and
# HOST_PORT.
#
# PAPERCLIP_PUBLIC_URL is not cosmetic. Paperclip builds its login and
# session-cookie redirects from it, so a value that does not match the address
# you actually type produces a login page that bounces you back to itself —
# the failure this repo hit on OpenProject, Nextcloud and n8n independently
# before it became a fixed convention.
ask_reachability() {
    prompt_host_port "$CONTAINER_PORT"

    if [[ -n "$HOST_PORT" ]]; then
        # Direct access: the URL must be the IP and port a browser will use,
        # not a domain that does not resolve yet.
        local server_ip
        server_ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
        [[ -n "$server_ip" ]] || server_ip="localhost"
        PUBLIC_URL="http://${server_ip}:${HOST_PORT}"
        print_info "Public URL set to $PUBLIC_URL (direct host port)."
    else
        prompt_domain "Public domain for Paperclip (e.g. agents.example.com): " "domain"
        PUBLIC_URL="https://$PROMPTED_DOMAIN"
        print_info "Public URL set to $PUBLIC_URL — point NGINX Proxy Manager at paperclip-app:$CONTAINER_PORT."
    fi
}

if [[ -f "$RUNTIME_DIR/docker-compose.yml" ]]; then
    print_info "Existing deployment found at $RUNTIME_DIR — its secrets and data are kept."

    # ── Reconfigure, so the first answer is not the permanent one ────────
    # Without this, moving from a direct host port to a domain behind NGINX
    # Proxy Manager means hand-editing .env — and getting PUBLIC_URL wrong
    # does not produce an error, it produces a login page that loops. That is
    # a bad thing to leave to memory and a text editor. Same lesson as the
    # "Reconfigure" option added to install_dockhub.sh, which existed because
    # the only route back to a question was a reset that destroyed the data.
    echo
    echo "  Currently reached at : $(read_env_value PUBLIC_URL "$RUNTIME_DIR/.env")"
    _cur_port="$(read_env_value HOST_PORT "$RUNTIME_DIR/.env")"
    echo "  Direct host port     : ${_cur_port:-none (via NGINX Proxy Manager)}"
    echo
    read -rp "Change how Paperclip is reached? (y/N): " _recfg || _recfg="n"
    if [[ "${_recfg,,}" == "y" ]]; then
        ask_reachability
        # Secrets are deliberately NOT regenerated here. Rewriting
        # BETTER_AUTH_SECRET would log every user out, and rewriting
        # POSTGRES_PASSWORD would lock the app out of its own database —
        # the .env would no longer match the password baked into the volume
        # when Postgres first initialised.
        set_env_value PUBLIC_URL "$PUBLIC_URL" "$RUNTIME_DIR/.env"
        # Emptied rather than deleted: read_env_value returns "" either way,
        # and the override generator below treats empty as "no port", so an
        # empty line switches direct access off without needing a delete.
        set_env_value HOST_PORT "${HOST_PORT:-}" "$RUNTIME_DIR/.env"
        print_info "Reconfigured. Secrets and data untouched."
    fi
else
    cp "$SOURCE_DIR/docker-compose.yml" "$RUNTIME_DIR/"

    ask_reachability
    prompt_mem_limit "paperclip" "2g"

    # ── Secrets ──────────────────────────────────────────────────────────
    # BETTER_AUTH_SECRET is marked required upstream with `:?`, i.e. their own
    # compose refuses to start without it. Generated here so it is never a
    # weak default and never the same on two hosts.
    umask 077
    {
        echo "# Generated by deploy.sh — do not commit. Secrets live here only."
        echo "PAPERCLIP_VERSION=latest"
        echo "POSTGRES_USER=paperclip"
        echo "POSTGRES_PASSWORD=$(generate_secret)"
        echo "POSTGRES_DB=paperclip"
        echo "BETTER_AUTH_SECRET=$(generate_secret_hex 32)"
        echo "PUBLIC_URL=$PUBLIC_URL"
        [[ -n "$MEM_LIMIT" ]] && echo "MEM_LIMIT=$MEM_LIMIT"
        [[ -n "$HOST_PORT" ]] && echo "HOST_PORT=$HOST_PORT"
    } > "$RUNTIME_DIR/.env"
    chmod 600 "$RUNTIME_DIR/.env"
    umask 022

    # The bind mount's target, created before compose does. Left to Docker it
    # would be created root-owned, and a container running as uid 1000 then
    # cannot write its own instance config.
    mkdir -p "$RUNTIME_DIR/state"

    print_info "Copied service files to $RUNTIME_DIR."
fi

# ── Regenerated every run, never hand-edited ────────────────────────────
# To change these later: edit MEM_LIMIT=/HOST_PORT= in $RUNTIME_DIR/.env (or
# delete the line), then rerun this script.
ENV_MEM_LIMIT="$(read_env_value MEM_LIMIT "$RUNTIME_DIR/.env" || true)"
ENV_HOST_PORT="$(read_env_value HOST_PORT "$RUNTIME_DIR/.env" || true)"

# This file is now always written, because it carries more than the optional
# extras: it decides whether the app joins main-net at all.
{
    echo "# Generated by deploy.sh on every run — never hand-edit."
    echo "services:"
    echo "  paperclip:"
    [[ -n "$ENV_MEM_LIMIT" ]] && echo "    mem_limit: $ENV_MEM_LIMIT"
    if [[ -n "$ENV_HOST_PORT" ]]; then
        echo "    ports:"
        echo "      - \"$ENV_HOST_PORT:$CONTAINER_PORT\""
    fi
    # ── The network decision ────────────────────────────────────────────
    # The full list is written out rather than just the addition, so this is
    # correct whether Compose merges a service's `networks` with the base
    # file's or replaces it. Under merge the duplicates collapse; under
    # replace this list is already complete. Emitting only "main-net" would
    # be right under one rule and would cut the app off from its own database
    # under the other.
    echo "    networks:"
    echo "      - paperclip-net"
    echo "      - ai-net"
    if [[ -z "$ENV_HOST_PORT" ]]; then
        echo "      - main-net"
    fi
} > "$RUNTIME_DIR/docker-compose.override.yml"

[[ -n "$ENV_MEM_LIMIT" ]] && print_info "Memory limit $ENV_MEM_LIMIT applied to paperclip-app (db stays unbounded)."
if [[ -n "$ENV_HOST_PORT" ]]; then
    print_info "Host port $ENV_HOST_PORT published for direct access."
    print_info "Not joined to 'main-net' — NGINX Proxy Manager is not in the path, so the"
    print_info "agents cannot reach the other services on it. This is the safer shape."
else
    print_warn "Joined to 'main-net' so NGINX Proxy Manager can reach it — which also means"
    print_warn "the agent harnesses in this container can reach everything else on it,"
    print_warn "including portainer:9000 (Docker socket) and NPM's admin interface."
    print_warn "Change both of their default passwords. See services/Multi-Agent/README.md."
fi

pull_with_progress "$RUNTIME_DIR"

print_info "Starting $SERVICE_NAME..."
(cd "$RUNTIME_DIR" && $COMPOSE_CMD up -d 2>&1 | tee -a "$LOGFILE") \
    || print_error "Failed to start $SERVICE_NAME. Check log: $LOGFILE"

# ── Self-test ───────────────────────────────────────────────────────────
# Probes from INSIDE the container against its own port, so this tests the
# app rather than the host's networking. `wait_for_container_ready` reports a
# crash-loop as a death instead of waiting out the full timeout — the whole
# reason it exists.
#
# The probe is a TCP connect, deliberately not an HTTP path: this deployment
# runs in "authenticated" mode, so every route worth naming answers 401 or
# 302 until you have an account. Treating that as failure would report a
# healthy service as broken, which is the mistake already made once on
# Hermes. What is being asserted here is narrow and true — the server is
# listening. Whether you can log in is the next section's job, and yours.
print_info "Waiting for Paperclip to accept connections..."
if wait_for_container_ready "paperclip-app" \
     "node -e 'require(\"net\").connect($CONTAINER_PORT,\"127.0.0.1\").on(\"connect\",()=>process.exit(0)).on(\"error\",()=>process.exit(1))'" \
     30 5; then
    print_info "Paperclip is listening on $CONTAINER_PORT."
else
    rc=$?
    if (( rc == 1 )); then
        print_warn "paperclip-app stopped while starting up. Its last lines are above."
    else
        print_warn "Paperclip did not answer within 150s. It may still be migrating the database on first boot."
    fi
    print_warn "Check with:  docker logs -f paperclip-app"
fi

echo
print_info "$SERVICE_NAME is running."
echo "  Proxy target for NPM : paperclip-app:$CONTAINER_PORT  (on main-net)"
echo "  Public URL           : $(read_env_value PUBLIC_URL "$RUNTIME_DIR/.env" || echo '?')"
echo "  Data                 : $RUNTIME_DIR/state   (agent teams, goals, tickets)"
echo "  Credentials file     : $RUNTIME_DIR/.env    (chmod 600)"
echo
echo "  First run: open the URL above and create the first account. Paperclip"
echo "  runs in 'authenticated' mode — there is no anonymous access, and no"
echo "  default password for anyone to find."
echo
echo "  Four agent harnesses are already inside the image — you do not install"
echo "  them, you just give them a key. Add whichever you have to"
echo "  $RUNTIME_DIR/.env and rerun this script:"
echo
echo "      ANTHROPIC_API_KEY=sk-ant-...   → Claude Code"
echo "      OPENAI_API_KEY=sk-...          → Codex"
echo "      GEMINI_API_KEY=...             → Gemini CLI"
echo "                                     → opencode (configured in the UI)"
echo
echo "  All are optional and passed straight through by env_file. Paperclip"
echo "  runs the harnesses as processes inside this container, so no extra"
echo "  container and no Docker socket is involved."

# ── A local provider, if one is running ─────────────────────────────────
# Reported rather than written into .env: which variable a harness wants
# differs per harness, and guessing wrong here would look like a working
# configuration that silently still calls the cloud.
detect_ai_provider
echo
if [[ -n "$AI_PROVIDER_NAME" ]]; then
    print_info "A local model provider is running on 'ai-net': $AI_PROVIDER_NAME"
    echo "  Paperclip is now on that network, so the harnesses can reach it. To"
    echo "  keep the work on your own hardware, point one at it in $RUNTIME_DIR/.env:"
    echo
    echo "      ANTHROPIC_BASE_URL=$AI_PROVIDER_BASE_URL     (Claude Code)"
    echo "      OPENAI_BASE_URL=$AI_PROVIDER_BASE_URL        (Codex)"
    echo
    echo "  Verify the route before trusting it:"
    echo "      docker exec paperclip-app node -e \"fetch('$AI_PROVIDER_BASE_URL').then(r=>console.log(r.status))\""
else
    echo
    echo "  No local model provider is running on 'ai-net'. Deploy one from the AI"
    echo "  category (Ollama, llama.cpp, LocalAI) and the harnesses can use it"
    echo "  instead of a cloud key — Paperclip is already attached to that network."
fi
print_tunnel_reminder_if_relevant
