#!/bin/bash
# SearXNG — private metasearch. Run with: bash deploy.sh
#
# Read services/Security/searxng/docker-compose.yml first — every non-obvious
# decision this script implements is explained there, sourced from upstream's
# current files rather than from a guide.
#
# The one thing worth knowing before reading on: `search.formats` defaults to
# [html] and NO environment variable changes it, so an instance nobody
# configured will serve a browser and refuse every API call. That is what the
# settings.yml written below is for.

set -euo pipefail

SERVICE_NAME="searxng"
SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNTIME_DIR="$HOME/docker/$SERVICE_NAME"
LOGFILE="$RUNTIME_DIR/deploy.log"

LIB_COMMON="$SOURCE_DIR/../../../lib/common.sh"
if [[ ! -f "$LIB_COMMON" ]]; then
    LIB_COMMON="$(mktemp -d)/common.sh"
    curl -fsSL -o "$LIB_COMMON" "https://raw.githubusercontent.com/IbrahimAljuhani/dockhub/main/lib/common.sh"
fi
# shellcheck source=/dev/null
source "$LIB_COMMON"

if [[ $EUID -eq 0 ]]; then
    print_error "This script must NOT be run as root. Please run as a regular user in the docker group."
fi

check_prerequisites
ensure_main_net

[[ -f "$SOURCE_DIR/docker-compose.yml" ]] || print_error "docker-compose.yml not found in $SOURCE_DIR."

mkdir -p "$RUNTIME_DIR"

# Every answer is initialised HERE, not inside the branch that asks for it.
# A variable first assigned inside a skippable block is unset under `set -u`
# on the path that skips it, and the run dies at the summary line with a
# message that names the wrong thing entirely. This has cost this repo two
# debugging sessions; it does not get to cost a third.
JSON_API="1"
ON_AI_NET="1"
SEARX_DOMAIN=""

if [[ -f "$RUNTIME_DIR/.env" ]]; then
    print_info "Existing deployment found at $RUNTIME_DIR — keeping its .env."
else
    echo
    print_info "SearXNG has two audiences, and they need different settings."
    print_info "The web UI works either way; the API does not exist until asked for."
    echo

    # ── Question 1: the API ──────────────────────────────────────────────
    # Upstream default is formats: [html]. An agent asking for JSON against
    # that instance gets refused, and the refusal does not explain itself.
    print_info "An agent or script needs JSON. A person with a browser does not."
    read -rp "$(print_ask "Enable the JSON API? (Y/n): ")" json_answer
    [[ "${json_answer,,}" == "n" ]] && JSON_API="0"

    # ── Question 2: reachability by agents ───────────────────────────────
    # Separate from question 1 on purpose: enabling JSON for your own scripts
    # on main-net is a different wish from putting the service on the agent
    # network. Bundling them would quietly widen one answer into two.
    if [[ "$JSON_API" == "1" ]]; then
        print_info "Agents (Hermes, OpenClaw, OpenHands) live on 'ai-net'."
        print_info "Joining it lets them query http://searxng-app:8080 directly."
        read -rp "$(print_ask "Join ai-net so agents can reach it? (Y/n): ")" ai_answer
        [[ "${ai_answer,,}" == "n" ]] && ON_AI_NET="0"
    else
        ON_AI_NET="0"
    fi

    # ── Question 3: the public URL ───────────────────────────────────────
    # base_url is not cosmetic: SearXNG builds absolute links from it, and
    # the OpenSearch description a browser uses to add it as a search engine
    # is one of them. Left unset behind a proxy, "add to browser" produces a
    # link back to the container.
    read -rp "$(print_ask "Will you reach it through a domain via NPM? (y/N): ")" dom_answer
    if [[ "${dom_answer,,}" == "y" ]]; then
        prompt_domain "Domain (e.g. search.example.com): " "domain"
        SEARX_DOMAIN="$PROMPTED_DOMAIN"
    fi

    prompt_mem_limit "searxng" "512m"
    prompt_host_port "8088"

    {
        echo "# Generated by deploy.sh. Values you may edit are marked."
        echo "#"
        echo "# SEARXNG_SECRET signs sessions and preference cookies. Changing it"
        echo "# invalidates saved preferences; it is not a password and is never"
        echo "# shown to a user."
        echo "SEARXNG_SECRET=$(generate_secret_urlsafe 32)"
        echo
        echo "# valkey holds the rate-limit counters. Reached by container name on"
        echo "# the private network — see docker-compose.yml, block 4."
        echo "SEARXNG_VALKEY_URL=valkey://searxng-valkey:6379/0"
        if [[ -n "$SEARX_DOMAIN" ]]; then
            echo "SEARXNG_BASE_URL=https://$SEARX_DOMAIN/"
            # Stored bare as well: the NPM block below wants a domain, not a
            # URL, and slicing one out of the other at the point of use is
            # how a trailing slash ends up in a Proxy Host field.
            echo "SEARXNG_DOMAIN=$SEARX_DOMAIN"
        fi
        echo
        echo "# DockHub's own record of your answers — re-read on every rerun."
        echo "SEARXNG_JSON_API=$JSON_API"
        echo "SEARXNG_ON_AI_NET=$ON_AI_NET"
    } > "$RUNTIME_DIR/.env"
    chmod 600 "$RUNTIME_DIR/.env"
    [[ -n "$MEM_LIMIT" ]] && echo "MEM_LIMIT=$MEM_LIMIT" >> "$RUNTIME_DIR/.env"
    [[ -n "$HOST_PORT" ]] && echo "HOST_PORT=$HOST_PORT" >> "$RUNTIME_DIR/.env"
    print_info "Generated .env at $RUNTIME_DIR."
fi

cp -f "$SOURCE_DIR/docker-compose.yml" "$RUNTIME_DIR/docker-compose.yml"

# Read every answer back from the file rather than trusting the variables
# above: on a rerun the questions never ran, and the file is the only truth.
ENV_JSON=$(read_env_value "SEARXNG_JSON_API" "$RUNTIME_DIR/.env")
ENV_AI_NET=$(read_env_value "SEARXNG_ON_AI_NET" "$RUNTIME_DIR/.env")
ENV_SECRET=$(read_env_value "SEARXNG_SECRET" "$RUNTIME_DIR/.env")
ENV_DOMAIN=$(read_env_value "SEARXNG_DOMAIN" "$RUNTIME_DIR/.env")
ENV_MEM_LIMIT=$(read_env_value "MEM_LIMIT" "$RUNTIME_DIR/.env")
ENV_HOST_PORT=$(read_env_value "HOST_PORT" "$RUNTIME_DIR/.env")

# ── settings.yml ─────────────────────────────────────────────────────────
# Written once, then never touched again. The image's entrypoint has the same
# rule ("if [ ! -f "$target_settings" ]"), so between the two of us nothing
# will ever overwrite an edit you made — including an image update.
#
# `use_default_settings: true` is what makes a nine-line file legal: the
# defaults (every engine, every category) are loaded first and only these
# keys are overridden. Without that line this file WOULD BE the whole
# configuration, and the instance would start with no engines at all.
mkdir -p "$RUNTIME_DIR/config"
if [[ -f "$RUNTIME_DIR/config/settings.yml" ]]; then
    print_info "settings.yml already exists — keeping it (your edits are safe)."
    if [[ "$ENV_JSON" == "1" ]] && ! grep -qE '^\s*-\s*json\s*$' "$RUNTIME_DIR/config/settings.yml"; then
        print_warn "You asked for the JSON API, but settings.yml has no 'json' under"
        print_warn "search.formats. This file is never rewritten, so add it by hand:"
        print_warn "  $RUNTIME_DIR/config/settings.yml"
    fi
else
    {
        echo "# Written by DockHub's deploy.sh on first run, and never again —"
        echo "# neither by this script nor by the image. Edit it freely."
        echo "#   https://docs.searxng.org/admin/settings/"
        echo
        echo "# Loads upstream's full configuration first; the keys below override"
        echo "# it. Remove this line and these nine lines become the ENTIRE config,"
        echo "# engines included — which is to say, none."
        echo "use_default_settings: true"
        echo
        echo "server:"
        echo "  secret_key: \"$ENV_SECRET\""
        echo "  # Serve result images through this instance so the originating site"
        echo "  # never sees your address. Upstream's own container template turns"
        echo "  # this on; the bare default has it off."
        echo "  image_proxy: true"
        if [[ "$ENV_JSON" == "1" ]]; then
            echo
            echo "search:"
            echo "  # The default is [html] alone, and no environment variable can"
            echo "  # change it. Without 'json' every API query is refused."
            echo "  formats:"
            echo "    - html"
            echo "    - json"
        fi
    } > "$RUNTIME_DIR/config/settings.yml"
    chmod 600 "$RUNTIME_DIR/config/settings.yml"
    print_info "Wrote config/settings.yml (JSON API: $( [[ "$ENV_JSON" == "1" ]] && echo enabled || echo off))."
fi

# ── override ─────────────────────────────────────────────────────────────
# Fully owned by this script — never hand-edit it. To change any of these,
# edit the matching key in .env and rerun.
if [[ -n "$ENV_MEM_LIMIT" || -n "$ENV_HOST_PORT" || "$ENV_AI_NET" == "1" ]]; then
    {
        echo "services:"
        echo "  searxng:"
        [[ -n "$ENV_MEM_LIMIT" ]] && echo "    mem_limit: $ENV_MEM_LIMIT"
        if [[ -n "$ENV_HOST_PORT" ]]; then
            echo "    ports:"
            echo "      - \"$ENV_HOST_PORT:8080\""
        fi
        if [[ "$ENV_AI_NET" == "1" ]]; then
            # A `networks:` key in an override REPLACES the list rather than
            # adding to it, so all three have to be named here — dropping
            # main-net would take NPM's path away as a side effect of saying
            # yes to agents.
            echo "    networks:"
            echo "      - searxng-net"
            echo "      - main-net"
            echo "      - ai-net"
        fi
        if [[ "$ENV_AI_NET" == "1" ]]; then
            echo "networks:"
            echo "  ai-net:"
            echo "    external: true"
        fi
    } > "$RUNTIME_DIR/docker-compose.override.yml"
else
    rm -f "$RUNTIME_DIR/docker-compose.override.yml"
fi

[[ "$ENV_AI_NET" == "1" ]] && ensure_ai_net

print_info "Starting $SERVICE_NAME..."
(cd "$RUNTIME_DIR" && $COMPOSE_CMD up -d 2>&1 | tee -a "$LOGFILE") \
    || print_error "Failed to start $SERVICE_NAME. Check log: $LOGFILE"

# ── self-test ────────────────────────────────────────────────────────────
# A container that is "Up" proves the process started, not that a search
# works. SearXNG answers on its port well before it is useful, and a refused
# format returns a clean HTTP 403 rather than a crash — so "Up" and "usable"
# are two different questions and only the second one matters here.
#
# The probe runs from the HOST against the container's own bridge address,
# NOT with `docker exec`. The image is built on searxng/base, whose contents
# are not a documented interface: guessing that curl, wget or python3 is on
# its PATH would produce a probe that fails for want of a tool and looks
# exactly like a service that never started. This repo has already paid for
# that lesson once, in services/AI-Agents/hermes/.
#
# The same rule applies to the host, and check_prerequisites does NOT require
# curl — it checks docker, compose and openssl. So the absence of curl is
# reported as "not tested", never as a failed test. An honest "I did not
# look" beats a confident wrong answer.
print_info "Waiting for it to answer..."
SELF_TEST="unknown"
SEARX_IP=""
command -v curl &>/dev/null || SELF_TEST="no-curl"
for _ in $(seq 1 20); do
    [[ "$SELF_TEST" == "no-curl" ]] && break
    if [[ -z "$SEARX_IP" ]]; then
        SEARX_IP=$(docker inspect -f \
            '{{range .NetworkSettings.Networks}}{{.IPAddress}} {{end}}' searxng-app 2>/dev/null \
            | tr ' ' '\n' | grep -m1 -E '^[0-9]' || true)
    fi
    if [[ -n "$SEARX_IP" ]]; then
        code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 5 \
            "http://$SEARX_IP:8080/search?q=dockhub&format=json" 2>/dev/null || echo 000)
        case "$code" in
            200) SELF_TEST="json-ok"; break ;;
            403) SELF_TEST="json-refused"; break ;;
            000) : ;;
            *)   SELF_TEST="http-$code"; break ;;
        esac
    fi
    sleep 3
done

echo
echo "════════════════════════════════════════════════════════════"
echo " ✅ SearXNG is running"
echo "════════════════════════════════════════════════════════════"
echo "📁 Directory:       $RUNTIME_DIR"
echo "⚙️  Settings:        $RUNTIME_DIR/config/settings.yml"
echo "🕸️  Networks:        searxng-net + main-net$( [[ "$ENV_AI_NET" == "1" ]] && echo " + ai-net" )"
[[ -n "$ENV_HOST_PORT" ]] && echo "🔌 Direct port:     $ENV_HOST_PORT → 8080"
echo

if [[ "$ENV_JSON" == "1" ]]; then
    case "$SELF_TEST" in
        json-ok)
            print_ok "JSON API answered 200 — an agent can query it now."
            ;;
        json-refused)
            print_warn "JSON API returned 403. 'json' is missing from search.formats"
            print_warn "in $RUNTIME_DIR/config/settings.yml — add it and restart:"
            print_warn "  (cd $RUNTIME_DIR && $COMPOSE_CMD restart)"
            ;;
        unknown)
            print_warn "No answer yet. It can take a minute on first start; check with:"
            print_warn "  docker logs -f searxng-app"
            ;;
        no-curl)
            print_info "Not tested — curl is not installed on this host. Verify with:"
            print_info "  docker logs --tail 20 searxng-app"
            ;;
        *)
            print_warn "JSON API returned $SELF_TEST — not the 200 expected."
            print_warn "  docker logs --tail 50 searxng-app"
            ;;
    esac
    echo
    if [[ "$ENV_AI_NET" == "1" ]]; then
        echo "Point an agent at it. For Hermes:"
        echo
        echo "   docker exec -it hermes hermes config set web.search_backend searxng"
        echo "   docker exec -it hermes sh -c 'echo SEARXNG_URL=http://searxng-app:8080 >> /opt/data/.env'"
        echo "   docker restart hermes"
        echo
        print_warn "Do that and queries stop leaving your server. Until then Hermes"
        print_warn "uses a rotating tier of five third-party endpoints, and does not"
        print_warn "log which one served you — see services/AI-Agents/README.md."
        echo
    fi
else
    print_info "JSON API is off — browser use only. To turn it on later, add"
    print_info "'json' under search.formats in config/settings.yml and restart."
    echo
fi

print_proxy_host_block "searxng-app" "8080" "http" "$ENV_DOMAIN"
print_tunnel_reminder_if_relevant
